name: Run

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        docker build . --tag myimage --build-arg NAME=akira --build-arg BUILD_NUMBER=${GITHUB_RUN_NUMBER}

    - name: run
      run: |
        docker run myimage
    